apiVersion: apps/v1
kind: Deployment
metadata:
  name: component-i4-0-test
  labels:
    app: component-i4-0-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: component-i4-0-test
  template:
    metadata:
      labels:
        app: component-i4-0-test
    spec:
      containers:
        - name: aas-manager
          image: ekhurtado/aas-manager:0.1.1
          imagePullPolicy: Always
          volumeMounts:
            - name: aas-archive
              mountPath: /aas_archive/
            - name: aas-archive-services
              mountPath: /aas_archive/services
              subPath: services
            - name: aas-archive-submodels
              mountPath: /aas_archive/submodels
              subPath: submodels
            - name: aas-archive-status
              mountPath: /aas_archive/status
              subPath: status
            - name: component-cm
              mountPath: /aas_archive/config

        - name: aas-core
          image: ekhurtado/aas-core:0.1.1
          imagePullPolicy: Always
          volumeMounts:
            - name: aas-archive
              mountPath: /aas_archive/
            - name: aas-archive-services
              mountPath: /aas_archive/services
              subPath: services
            - name: aas-archive-submodels
              mountPath: /aas_archive/submodels
              subPath: submodels
            - name: aas-archive-status
              mountPath: /aas_archive/status
              subPath: status
            - name: component-cm
              mountPath: /aas_archive/config
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        # The shared directory for holding the files
        - name: aas-archive
          emptyDir: { }
        # Subvolume related to services
        - name: aas-archive-services
        # Subvolume related to status
        - name: aas-archive-submodels
        # Subvolume related to status
        - name: aas-archive-status
        # The configmap with all the configuration
        - name: component-cm
          configMap:
            name: component-i4-0-cm

